__all__ = [
    "ENTITY_TYPE_URL", "ENTITY_TYPE_SHORTENED_URL", "ENTITY_TYPE_SUSPICIOUS_TLD",
    "ENTITY_TYPE_DOMAIN", "ENTITY_TYPE_EMAIL", "ENTITY_TYPE_PHONE_INDIAN",
    "ENTITY_TYPE_PHONE_INTERNATIONAL", "ENTITY_TYPE_UPI_ID", "ENTITY_TYPE_QR_KEYWORD",
    "ENTITY_TYPE_BANK_NAME", "ENTITY_TYPE_GOVERNMENT", "ENTITY_TYPE_CURRENCY",
    "ENTITY_TYPE_OTP_CODE", "ENTITY_TYPE_IP_ADDRESS", "ENTITY_TYPE_SOCIAL_HANDLE",
    "ENTITY_TYPE_IFSC_CODE", "ENTITY_TYPE_BANK_ACCOUNT", "ENTITY_TYPE_TRACKING_ID",
    "ENTITY_TYPE_TRANSACTION_ID",
    "ENTITY_SOURCE_REGEX", "ENTITY_SOURCE_KEYWORD", "ENTITY_SOURCE_INFERENCE",
    "TIMELINE_STAGES",
    "REFINEMENT_STATUS_APPLIED", "REFINEMENT_STATUS_SKIPPED",
    "REFINEMENT_CATEGORY_FP", "REFINEMENT_CATEGORY_FN", "REFINEMENT_CATEGORY_STABILITY",
    "REFINEMENT_PRIORITY_HIGH", "REFINEMENT_PRIORITY_MEDIUM", "REFINEMENT_PRIORITY_LOW",
    "REFINEMENT_VERY_HIGH_BAND", "REFINEMENT_HIGH_BAND", "REFINEMENT_MEDIUM_BAND", "REFINEMENT_LOW_BAND",
    "REFINEMENT_BOUNDARY_PROXIMITY", "REFINEMENT_CONFIDENCE_THRESHOLD_LOW", "REFINEMENT_CONFIDENCE_THRESHOLD_HIGH",
    "REFINEMENT_MAX_FP_ADJUSTMENT", "REFINEMENT_MAX_FN_ADJUSTMENT",
    "INVESTIGATION_ARTEFACT_TYPES", "INVESTIGATION_CAMPAIGN_CONFIDENCE_THRESHOLD",
    "INVESTIGATION_INDICATOR_SHARED_PHONE", "INVESTIGATION_INDICATOR_SHARED_DOMAIN",
    "INVESTIGATION_INDICATOR_SHARED_UPI", "INVESTIGATION_INDICATOR_SHARED_EMAIL",
    "INVESTIGATION_INDICATOR_SHARED_BANK", "INVESTIGATION_INDICATOR_REPEATED_WORDING",
    "INVESTIGATION_INDICATOR_SAME_FAMILY",
    "INVESTIGATION_EVENT_MESSAGE", "INVESTIGATION_EVENT_CLASSIFICATION",
    "INVESTIGATION_EVENT_LINK", "INVESTIGATION_EVENT_PAYMENT", "INVESTIGATION_EVENT_OTP",
    "INVESTIGATION_EVENT_THREAT", "INVESTIGATION_EVENT_IDENTITY", "INVESTIGATION_EVENT_QR",
    "INVESTIGATION_EVENT_HIGH_RISK_ENTITY",
    "INVESTIGATION_NODE_ARTEFACT", "INVESTIGATION_NODE_ENTITY", "INVESTIGATION_NODE_CAMPAIGN",
    "INVESTIGATION_NODE_INDICATOR", "INVESTIGATION_EDGE_MENTIONS", "INVESTIGATION_EDGE_BELONGS_TO",
    "INVESTIGATION_EVIDENCE_FAMILY_BOOST", "INVESTIGATION_EVIDENCE_WORDING_BOOST",
    "INVESTIGATION_EVIDENCE_SHARED_PHONE_BOOST", "INVESTIGATION_EVIDENCE_SHARED_DOMAIN_BOOST",
    "INVESTIGATION_EVIDENCE_SHARED_UPI_BOOST", "INVESTIGATION_EVIDENCE_SHARED_EMAIL_BOOST",
    "INVESTIGATION_EVIDENCE_SHARED_BANK_BOOST", "INVESTIGATION_EVIDENCE_PER_SHARED_ENTITY_BOOST",
    "INVESTIGATION_EVIDENCE_MAX_SHARED_ENTITY_BOOST",
    "INVESTIGATION_RISK_CRITICAL", "INVESTIGATION_RISK_HIGH", "INVESTIGATION_RISK_MEDIUM",
    "INVESTIGATION_RISK_REDUNDANCY_BOOST", "INVESTIGATION_RISK_REDUNDANCY_THRESHOLD",
    "INVESTIGATION_RISK_HE_THRESHOLD", "INVESTIGATION_RISK_SINGLE_ARTEFACT_PENALTY",
    "SERVICE_NAME", "API_VERSION",
]

from typing import Dict, FrozenSet, Tuple

ENTITY_TYPE_URL: str = "url"
ENTITY_TYPE_SHORTENED_URL: str = "shortened_url"
ENTITY_TYPE_SUSPICIOUS_TLD: str = "suspicious_tld"
ENTITY_TYPE_DOMAIN: str = "domain"
ENTITY_TYPE_EMAIL: str = "email"
ENTITY_TYPE_PHONE_INDIAN: str = "phone_indian"
ENTITY_TYPE_PHONE_INTERNATIONAL: str = "phone_international"
ENTITY_TYPE_UPI_ID: str = "upi_id"
ENTITY_TYPE_QR_KEYWORD: str = "qr_keyword"
ENTITY_TYPE_BANK_NAME: str = "bank_name"
ENTITY_TYPE_GOVERNMENT: str = "government_entity"
ENTITY_TYPE_CURRENCY: str = "currency_amount"
ENTITY_TYPE_OTP_CODE: str = "otp_code"
ENTITY_TYPE_IP_ADDRESS: str = "ip_address"
ENTITY_TYPE_SOCIAL_HANDLE: str = "social_handle"
ENTITY_TYPE_IFSC_CODE: str = "ifsc_code"
ENTITY_TYPE_BANK_ACCOUNT: str = "bank_account"
ENTITY_TYPE_TRACKING_ID: str = "tracking_id"
ENTITY_TYPE_TRANSACTION_ID: str = "transaction_id"

ENTITY_SOURCE_REGEX: str = "regex"
ENTITY_SOURCE_KEYWORD: str = "keyword"
ENTITY_SOURCE_INFERENCE: str = "inference"

TIMELINE_STAGES: Tuple[Dict[str, str], ...] = (
    {"stage": 1, "event": "Message Received", "description": "Message submitted for analysis."},
    {"stage": 2, "event": "Content Analysed", "description": "ML model and rule engine processed the message content."},
    {"stage": 3, "event": "Entities Extracted", "description": "Threat intelligence extracted URLs, phone numbers, and other indicators."},
    {"stage": 4, "event": "Evidence Correlated", "description": "Evidence engine correlated indicators and detected conflicts."},
    {"stage": 5, "event": "Risk Assessed", "description": "Assessment engine computed unified risk score."},
    {"stage": 6, "event": "Report Generated", "description": "Investigation report compiled with all findings."},
)

REFINEMENT_STATUS_APPLIED: str = "applied"
REFINEMENT_STATUS_SKIPPED: str = "skipped"
REFINEMENT_CATEGORY_FP: str = "fp_reduction"
REFINEMENT_CATEGORY_FN: str = "fn_reduction"
REFINEMENT_CATEGORY_STABILITY: str = "stability"

REFINEMENT_PRIORITY_HIGH: str = "HIGH"
REFINEMENT_PRIORITY_MEDIUM: str = "MEDIUM"
REFINEMENT_PRIORITY_LOW: str = "LOW"

REFINEMENT_VERY_HIGH_BAND: int = 85
REFINEMENT_HIGH_BAND: int = 65
REFINEMENT_MEDIUM_BAND: int = 40
REFINEMENT_LOW_BAND: int = 20

REFINEMENT_BOUNDARY_PROXIMITY: int = 3
REFINEMENT_CONFIDENCE_THRESHOLD_LOW: float = 0.45
REFINEMENT_CONFIDENCE_THRESHOLD_HIGH: float = 0.55

REFINEMENT_MAX_FP_ADJUSTMENT: int = 30
REFINEMENT_MAX_FN_ADJUSTMENT: int = 30

INVESTIGATION_ARTEFACT_TYPES: Tuple[str, ...] = (
    "sms", "screenshot", "whatsapp", "email", "telegram", "chat", "text",
)
INVESTIGATION_CAMPAIGN_CONFIDENCE_THRESHOLD: float = 0.3

INVESTIGATION_INDICATOR_SHARED_PHONE: str = "shared_phone"
INVESTIGATION_INDICATOR_SHARED_DOMAIN: str = "shared_domain"
INVESTIGATION_INDICATOR_SHARED_UPI: str = "shared_upi"
INVESTIGATION_INDICATOR_SHARED_EMAIL: str = "shared_email"
INVESTIGATION_INDICATOR_SHARED_BANK: str = "shared_bank"
INVESTIGATION_INDICATOR_REPEATED_WORDING: str = "repeated_wording"
INVESTIGATION_INDICATOR_SAME_FAMILY: str = "same_family"

INVESTIGATION_EVENT_MESSAGE: str = "message_received"
INVESTIGATION_EVENT_CLASSIFICATION: str = "classification"
INVESTIGATION_EVENT_LINK: str = "link_shared"
INVESTIGATION_EVENT_PAYMENT: str = "payment_requested"
INVESTIGATION_EVENT_OTP: str = "otp_requested"
INVESTIGATION_EVENT_THREAT: str = "threat_escalation"
INVESTIGATION_EVENT_IDENTITY: str = "identity_requested"
INVESTIGATION_EVENT_QR: str = "qr_requested"
INVESTIGATION_EVENT_HIGH_RISK_ENTITY: str = "high_risk_entity"

INVESTIGATION_NODE_ARTEFACT: str = "artefact"
INVESTIGATION_NODE_ENTITY: str = "entity"
INVESTIGATION_NODE_CAMPAIGN: str = "campaign"
INVESTIGATION_NODE_INDICATOR: str = "indicator"
INVESTIGATION_EDGE_MENTIONS: str = "mentions"
INVESTIGATION_EDGE_BELONGS_TO: str = "belongs_to_campaign"

INVESTIGATION_EVIDENCE_FAMILY_BOOST: float = 0.25
INVESTIGATION_EVIDENCE_WORDING_BOOST: float = 0.15
INVESTIGATION_EVIDENCE_SHARED_PHONE_BOOST: float = 0.20
INVESTIGATION_EVIDENCE_SHARED_DOMAIN_BOOST: float = 0.15
INVESTIGATION_EVIDENCE_SHARED_UPI_BOOST: float = 0.20
INVESTIGATION_EVIDENCE_SHARED_EMAIL_BOOST: float = 0.10
INVESTIGATION_EVIDENCE_SHARED_BANK_BOOST: float = 0.15
INVESTIGATION_EVIDENCE_PER_SHARED_ENTITY_BOOST: float = 0.05
INVESTIGATION_EVIDENCE_MAX_SHARED_ENTITY_BOOST: float = 0.20

INVESTIGATION_RISK_CRITICAL: int = 76
INVESTIGATION_RISK_HIGH: int = 51
INVESTIGATION_RISK_MEDIUM: int = 21
INVESTIGATION_RISK_REDUNDANCY_BOOST: int = 5
INVESTIGATION_RISK_REDUNDANCY_THRESHOLD: int = 3
INVESTIGATION_RISK_HE_THRESHOLD: int = 3
INVESTIGATION_RISK_SINGLE_ARTEFACT_PENALTY: float = 0.9

SERVICE_NAME: str = "Kaaval"
API_VERSION: str = "1.0.0"
