__all__ = [
    "RISK_HIGH", "RISK_MEDIUM", "RISK_LOW",
    "SEVERITY_CRITICAL", "SEVERITY_HIGH", "SEVERITY_MEDIUM", "SEVERITY_LOW", "SEVERITY_VERY_LOW",
    "PRIORITY_URGENT", "PRIORITY_HIGH", "PRIORITY_NORMAL", "PRIORITY_LOW",
    "DECISION_CRITICAL", "DECISION_HIGH_RISK", "DECISION_SUSPICIOUS", "DECISION_LOW_RISK", "DECISION_SAFE",
    "ASSESSMENT_IMMEDIATE_ACTION", "ASSESSMENT_INVESTIGATION", "ASSESSMENT_REVIEW", "ASSESSMENT_NORMAL",
    "CONFIDENCE_HIGH", "CONFIDENCE_MEDIUM", "CONFIDENCE_LOW",
    "ACTION_BLOCK_REPORT", "ACTION_DO_NOT_INTERACT", "ACTION_VERIFY", "ACTION_MONITOR", "ACTION_IGNORE",
    "ML_LABEL_SCAM", "ML_LABEL_SAFE",
    "NODE_TYPE_ML", "NODE_TYPE_RULE", "NODE_TYPE_INDICATOR", "NODE_TYPE_ENTITY",
    "NODE_TYPE_URL", "NODE_TYPE_PHONE", "NODE_TYPE_EMAIL", "NODE_TYPE_UPI", "NODE_TYPE_BANK",
    "NODE_TYPE_GOVERNMENT", "NODE_TYPE_CONFLICT", "NODE_TYPE_CORRELATION",
    "EDGE_SUPPORTS", "EDGE_CONTRADICTS", "EDGE_STRENGTHENS", "EDGE_WEAKENS", "EDGE_DUPLICATES",
    "EVIDENCE_PRIMARY", "EVIDENCE_SUPPORTING", "EVIDENCE_WEAK", "EVIDENCE_CONTRADICTORY", "EVIDENCE_IGNORED",
]

from typing import FrozenSet, Tuple

RISK_HIGH: str = "high"
RISK_MEDIUM: str = "medium"
RISK_LOW: str = "low"

SEVERITY_CRITICAL: str = "CRITICAL"
SEVERITY_HIGH: str = "HIGH"
SEVERITY_MEDIUM: str = "MEDIUM"
SEVERITY_LOW: str = "LOW"
SEVERITY_VERY_LOW: str = "VERY LOW"

PRIORITY_URGENT: str = "URGENT"
PRIORITY_HIGH: str = "HIGH"
PRIORITY_NORMAL: str = "NORMAL"
PRIORITY_LOW: str = "LOW"

DECISION_CRITICAL: str = "CRITICAL"
DECISION_HIGH_RISK: str = "HIGH RISK"
DECISION_SUSPICIOUS: str = "SUSPICIOUS"
DECISION_LOW_RISK: str = "LOW RISK"
DECISION_SAFE: str = "SAFE"

ASSESSMENT_IMMEDIATE_ACTION: str = "Suitable for immediate action"
ASSESSMENT_INVESTIGATION: str = "Suitable for security investigation"
ASSESSMENT_REVIEW: str = "Further assessment required"
ASSESSMENT_NORMAL: str = "Suitable for normal communication"

CONFIDENCE_HIGH: str = "HIGH"
CONFIDENCE_MEDIUM: str = "MEDIUM"
CONFIDENCE_LOW: str = "LOW"

ACTION_BLOCK_REPORT: str = "Block and report"
ACTION_DO_NOT_INTERACT: str = "Do not interact"
ACTION_VERIFY: str = "Verify independently"
ACTION_MONITOR: str = "Monitor"
ACTION_IGNORE: str = "Ignore"

ML_LABEL_SCAM: str = "scam"
ML_LABEL_SAFE: str = "safe"

NODE_TYPE_ML: str = "ml_prediction"
NODE_TYPE_RULE: str = "rule_score"
NODE_TYPE_INDICATOR: str = "indicator"
NODE_TYPE_ENTITY: str = "entity"
NODE_TYPE_URL: str = "url"
NODE_TYPE_PHONE: str = "phone"
NODE_TYPE_EMAIL: str = "email"
NODE_TYPE_UPI: str = "upi"
NODE_TYPE_BANK: str = "bank"
NODE_TYPE_GOVERNMENT: str = "government"
NODE_TYPE_CONFLICT: str = "conflict"
NODE_TYPE_CORRELATION: str = "correlation"

EDGE_SUPPORTS: str = "supports"
EDGE_CONTRADICTS: str = "contradicts"
EDGE_STRENGTHENS: str = "strengthens"
EDGE_WEAKENS: str = "weakens"
EDGE_DUPLICATES: str = "duplicates"

EVIDENCE_PRIMARY: str = "primary"
EVIDENCE_SUPPORTING: str = "supporting"
EVIDENCE_WEAK: str = "weak"
EVIDENCE_CONTRADICTORY: str = "contradictory"
EVIDENCE_IGNORED: str = "ignored"
