import type { AnalysisResponse } from '@/types';
import type { DemoCase } from '@/features/demo/types';

function makeResult(overrides: Partial<AnalysisResponse>): AnalysisResponse {
  const def: AnalysisResponse = {
    prediction: 'scam', confidence: 0.92, rule_score: 85, rule_label: 'HIGH_RISK',
    reasons: [], suggested_action: 'block', summary: '', risk_level: 'high', scam_category: 'phishing',
    detected_indicators: [], threats: [], recommended_actions: [],
    entities: [], entity_summary: { total_entities: 0, by_type: {}, threat_indicators: [] },
    entity_risk: { high: [], medium: [], low: [] },
    decision_score: 85, decision_level: 'suspicious', decision_reasoning: '',
    supporting_evidence: [], conflicting_evidence: [],
    confidence_breakdown: { ml: 0.9, rules: 0.85, entities: 0.7, explanation: 0.8, overall: 0.92 },
    risk_breakdown: { credential_theft: 0, financial_loss: 0, identity_theft: 0, malware: 0, social_engineering: 0 },
    recommended_priority: 'high', recommended_action: 'block',
    assessment_score: 85, assessment_band: 'requires investigation', assessment_confidence: 'high',
    assessment_summary: '', business_reason: '', technical_reason: '',
    review_required: false, manual_review_reason: '', investigation_report: {},
  };
  return { ...def, ...overrides };
}

export const SAMPLE_CASES: DemoCase[] = [
  {
    id: 'bank-phishing',
    title: 'Bank Phishing Campaign',
    category: 'Phishing',
    difficulty: 'intermediate',
    description: 'Fake bank login page harvesting credentials via SMS phishing. Contains spoofed bank domain, SSL certificate mismatch, and credential theft indicators.',
    icon: '🏦',
    result: makeResult({
      prediction: 'scam', confidence: 0.96, risk_level: 'critical', scam_category: 'phishing',
      summary: 'Sophisticated bank phishing site mimicking State Bank of India with real SSL certificate on lookalike domain.',
      reasons: ['Lookalike domain registered 48 hours ago', 'SSL certificate does not match legitimate bank', 'Form action points to external IP', 'Contains JavaScript keylogger'],
      suggested_action: 'block', rule_score: 92, rule_label: 'CRITICAL_RISK',
      decision_score: 94, decision_level: 'critical',
      decision_reasoning: 'Domain age (<2 days), SSL mismatch, external form submission, and JavaScript keylogger detected.',
      entities: [
        { value: 'sbi-secure-login.com', type: 'domain', confidence: 0.98, source: 'url_parser', risk: 'high', risk_reason: 'Lookalike domain, registered 48h ago' },
        { value: '185.234.72.18', type: 'ip', confidence: 0.95, source: 'dns_lookup', risk: 'high', risk_reason: 'IP in known C2 blocklist' },
        { value: '+91-9876543210', type: 'phone', confidence: 0.85, source: 'entity_extractor', risk: 'medium', risk_reason: 'SMS origin number, multiple reports' },
      ],
      entity_summary: { total_entities: 3, by_type: { domain: 1, ip: 1, phone: 1 }, threat_indicators: ['Lookalike domain', 'C2 IP'] },
      entity_risk: { high: [
        { value: 'sbi-secure-login.com', type: 'domain', confidence: 0.98, source: 'url_parser', risk: 'high', risk_reason: 'Lookalike domain, registered 48h ago' },
        { value: '185.234.72.18', type: 'ip', confidence: 0.95, source: 'dns_lookup', risk: 'high', risk_reason: 'IP in known C2 blocklist' },
      ], medium: [
        { value: '+91-9876543210', type: 'phone', confidence: 0.85, source: 'entity_extractor', risk: 'medium', risk_reason: 'SMS origin number, multiple reports' },
      ], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'technical', source: 'domain_analysis', description: 'Domain registered 48 hours ago via privacy-enabled registrar', severity: 'high', confidence: 0.98, weight: 9 },
        { id: 'ev2', type: 'technical', source: 'ssl_analysis', description: 'SSL certificate issued to different organization than expected bank', severity: 'high', confidence: 0.95, weight: 8 },
        { id: 'ev3', type: 'behavioral', source: 'page_analysis', description: 'Login form submits credentials to external IP via POST request', severity: 'critical', confidence: 0.97, weight: 10 },
        { id: 'ev4', type: 'technical', source: 'js_analysis', description: 'JavaScript keylogger captures keystrokes before form submission', severity: 'critical', confidence: 0.93, weight: 9 },
      ],
      conflicting_evidence: [
        { id: 'cev1', type: 'technical', source: 'ssl_check', description: 'Valid SSL certificate present (Let\'s Encrypt)', severity: 'low', confidence: 0.6, weight: 2 },
      ],
      threats: ['Credential harvesting via phishing page', 'Keylogger script injection', 'SaaS landing page abuse', 'Brand impersonation'],
      detected_indicators: ['Lookalike domain pattern', 'SSL organization mismatch', 'External form submission', 'JavaScript keylogger', 'Recently registered domain', 'Privacy-enabled WHOIS'],
      recommended_actions: ['Block domain at DNS level', 'Report to CERT-In', 'Notify bank security team', 'Warn users who received SMS', 'Add to threat intelligence feed'],
      recommended_priority: 'urgent', recommended_action: 'block',
      assessment_score: 96, assessment_band: 'requires immediate action', assessment_confidence: 'high',
      assessment_summary: 'Confirmed credential theft operation targeting bank customers.',
      business_reason: 'Active credential theft campaign targeting bank customers.',
      technical_reason: 'Lookalike domain with keylogger and external C2 communication.',
      review_required: true, manual_review_reason: 'Confirmed active phishing campaign — escalation to SOC team required',
      risk_breakdown: { credential_theft: 95, financial_loss: 85, identity_theft: 60, malware: 20, social_engineering: 90 },
      connector_matches: [
        { connector_name: 'ThreatFox', source: 'abuse.ch', verdict: 'malicious', confidence: 0.95 },
        { connector_name: 'URLScan', source: 'urlscan.io', verdict: 'phishing', confidence: 0.92 },
      ],
      knowledge_matches: [
        { pattern: 'Bank phishing — lookalike domain', label: 'Bank Phishing v2', similarity: 0.94 },
        { pattern: 'Credential harvesting via SSL', label: 'Fake SSL Phishing', similarity: 0.88 },
      ],
      threat_intel_fusion: { overall_verdict: 'malicious', overall_confidence: 0.94, overall_severity: 'critical', agreement_score: 0.91, source_count: 3 },
      investigation_report: { technique: 'Phishing', ttps: ['T1566', 'T1534'], iocs: ['sbi-secure-login.com', '185.234.72.18'] },
    }),
  },
  {
    id: 'fake-kyc', title: 'Fake KYC Scam', category: 'Identity Theft', difficulty: 'beginner',
    description: 'Fake KYC update message with link to credential harvesting site. Targets banking customers with urgency tactics.',
    icon: '🪪',
    result: makeResult({
      prediction: 'scam', confidence: 0.89, risk_level: 'high', scam_category: 'identity_theft',
      summary: 'Fake KYC update SMS campaign using urgency tactics. Link leads to credential harvesting page.',
      reasons: ['Urgency language: "KYC will be blocked"', 'Shortened URL redirecting to unknown domain', 'Request for sensitive documents', 'No HTTPS on landing page'],
      suggested_action: 'block', rule_score: 78, rule_label: 'HIGH_RISK', decision_score: 82, decision_level: 'suspicious',
      decision_reasoning: 'Social engineering via urgency + document harvesting. Multiple users reported same message pattern.',
      entities: [
        { value: 'kyc-update-now.com', type: 'domain', confidence: 0.92, source: 'url_parser', risk: 'high', risk_reason: 'Newly registered domain for KYC phishing' },
        { value: 'Customer Support', type: 'sender', confidence: 0.78, source: 'message_analysis', risk: 'medium', risk_reason: 'Spoofed sender name' },
      ],
      entity_summary: { total_entities: 2, by_type: { domain: 1, sender: 1 }, threat_indicators: ['KYC phishing domain'] },
      entity_risk: { high: [{ value: 'kyc-update-now.com', type: 'domain', confidence: 0.92, source: 'url_parser', risk: 'high', risk_reason: 'KYC phishing domain' }], medium: [{ value: 'Customer Support', type: 'sender', confidence: 0.78, source: 'message_analysis', risk: 'medium', risk_reason: 'Spoofed sender' }], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'message', source: 'sms_analysis', description: 'Message uses urgency: "Your KYC will be blocked in 24 hours"', severity: 'high', confidence: 0.91, weight: 8 },
        { id: 'ev2', type: 'technical', source: 'url_analysis', description: 'Shortened URL redirects to newly registered domain', severity: 'high', confidence: 0.88, weight: 7 },
        { id: 'ev3', type: 'behavioral', source: 'page_analysis', description: 'Page requests Aadhaar card, PAN card, and bank account number', severity: 'critical', confidence: 0.94, weight: 9 },
      ],
      conflicting_evidence: [],
      threats: ['Identity document harvesting', 'Bank account takeover', 'Social engineering via authority impersonation'],
      detected_indicators: ['Urgency language pattern', 'Shortened URL', 'Document harvesting form', 'New domain registration', 'Brand impersonation'],
      recommended_actions: ['Block domain', 'Warn users about KYC phishing campaign', 'Report to cybercrime portal', 'Alert bank security team'],
      recommended_priority: 'high', recommended_action: 'block',
      assessment_score: 85, assessment_band: 'requires investigation', assessment_confidence: 'high',
      assessment_summary: 'KYC-themed identity theft campaign. Targets sensitive documents via urgency-based social engineering.',
      business_reason: 'Identity theft campaign targeting customers with fake KYC notice.',
      technical_reason: 'Newly registered phishing domain with document harvesting form.',
      risk_breakdown: { credential_theft: 20, financial_loss: 70, identity_theft: 90, malware: 10, social_engineering: 85 },
    }),
  },
  {
    id: 'courier-scam', title: 'Courier Parcel Scam', category: 'Social Engineering', difficulty: 'beginner',
    description: 'Fake courier delivery notification with malicious APK attachment. Claims undelivered package requires payment.',
    icon: '📦',
    result: makeResult({
      prediction: 'scam', confidence: 0.87, risk_level: 'high', scam_category: 'social_engineering',
      summary: 'Fake courier delivery SMS with APK attachment posing as tracking app. Installs spyware to steal banking credentials.',
      reasons: ['Unsolicited courier notification', 'APK file disguised as PDF', 'Requests SMS and phone permissions', 'Multiple reports on same tracking number'],
      suggested_action: 'warn', rule_score: 75, rule_label: 'HIGH_RISK', decision_score: 80, decision_level: 'suspicious',
      decision_reasoning: 'APK sideloading attack vector combined with social engineering.',
      entities: [
        { value: 'track-delivery.apk', type: 'file', confidence: 0.94, source: 'attachment_analysis', risk: 'high', risk_reason: 'APK file disguised as PDF tracking document' },
        { value: 'DHL-India', type: 'sender', confidence: 0.72, source: 'message_analysis', risk: 'medium', risk_reason: 'Impersonated courier brand' },
      ],
      entity_summary: { total_entities: 2, by_type: { file: 1, sender: 1 }, threat_indicators: ['Malicious APK', 'Brand impersonation'] },
      entity_risk: { high: [{ value: 'track-delivery.apk', type: 'file', confidence: 0.94, source: 'attachment_analysis', risk: 'high', risk_reason: 'Malicious APK' }], medium: [{ value: 'DHL-India', type: 'sender', confidence: 0.72, source: 'message_analysis', risk: 'medium', risk_reason: 'Impersonated courier' }], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'message', source: 'sms_analysis', description: 'Unsolicited courier delivery notification with tracking link', severity: 'medium', confidence: 0.83, weight: 6 },
        { id: 'ev2', type: 'technical', source: 'file_analysis', description: 'APK file disguised as PDF — requests SMS read and phone permissions', severity: 'high', confidence: 0.94, weight: 9 },
      ],
      conflicting_evidence: [],
      threats: ['Spyware installation via fake APK', 'SMS interception for OTP theft', 'Banking credential theft'],
      detected_indicators: ['APK file in SMS', 'Brand impersonation', 'Unsolicited delivery notification', 'Excessive app permissions'],
      recommended_actions: ['Warn users about courier scam', 'Block APK download link', 'Add SMS filter rule', 'Report to CERT-In'],
      recommended_priority: 'high', recommended_action: 'warn',
      assessment_score: 82, assessment_band: 'requires investigation', assessment_confidence: 'high',
      assessment_summary: 'Social engineering campaign using fake courier notifications to distribute spyware APK.',
      risk_breakdown: { credential_theft: 75, financial_loss: 60, identity_theft: 40, malware: 90, social_engineering: 80 },
    }),
  },
  {
    id: 'upi-fraud', title: 'UPI Payment Fraud', category: 'Financial Fraud', difficulty: 'intermediate',
    description: 'Fake UPI payment request with social engineering call. Victim tricked into approving fraudulent payment.',
    icon: '💳',
    result: makeResult({
      prediction: 'scam', confidence: 0.93, risk_level: 'critical', scam_category: 'financial_fraud',
      summary: 'UPI fraud via fake payment request + social engineering call. Attacker claims refund and tricks victim into approving Collect request.',
      reasons: ['Collect request disguised as refund', 'Spoofed caller ID from "bank"', 'Request for UPI PIN', 'Multiple failed transactions before success'],
      suggested_action: 'block', rule_score: 88, rule_label: 'CRITICAL_RISK', decision_score: 90, decision_level: 'critical',
      decision_reasoning: 'Classic UPI refund scam pattern. Social engineering combined with payment system abuse.',
      entities: [
        { value: 'UPI@icici', type: 'vpa', confidence: 0.91, source: 'transaction_analysis', risk: 'high', risk_reason: 'Fraudulent VPA used for Collect requests' },
        { value: '+91-9876543210', type: 'phone', confidence: 0.88, source: 'caller_id', risk: 'high', risk_reason: 'Spoofed caller ID impersonating bank' },
      ],
      entity_summary: { total_entities: 2, by_type: { vpa: 1, phone: 1 }, threat_indicators: ['Fraudulent VPA', 'Spoofed caller ID'] },
      entity_risk: { high: [
        { value: 'UPI@icici', type: 'vpa', confidence: 0.91, source: 'transaction_analysis', risk: 'high', risk_reason: 'Fraudulent VPA' },
        { value: '+91-9876543210', type: 'phone', confidence: 0.88, source: 'caller_id', risk: 'high', risk_reason: 'Spoofed caller ID' },
      ], medium: [], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'behavioral', source: 'call_analysis', description: 'Caller claimed to be bank representative processing a refund', severity: 'high', confidence: 0.92, weight: 8 },
        { id: 'ev2', type: 'transactional', source: 'payment_analysis', description: 'Multiple UPI Collect requests from unknown VPA', severity: 'critical', confidence: 0.95, weight: 9 },
        { id: 'ev3', type: 'behavioral', source: 'social_engineering', description: 'Caller requested UPI PIN to "verify identity"', severity: 'critical', confidence: 0.94, weight: 10 },
      ],
      conflicting_evidence: [],
      threats: ['UPI fraud via Collect request abuse', 'Social engineering for payment approval', 'VPA spoofing'],
      detected_indicators: ['UPI Collect request from unknown VPA', 'Caller ID spoofing', 'Refund pretext', 'PIN request'],
      recommended_actions: ['Block fraudulent VPA', 'Report to NPCI', 'Warn user about UPI refund scam pattern', 'Add fraud alert to UPI handle'],
      recommended_priority: 'urgent', recommended_action: 'block',
      assessment_score: 92, assessment_band: 'requires immediate action', assessment_confidence: 'high',
      assessment_summary: 'Confirmed UPI fraud with active social engineering. Immediate action required to block VPA.',
      business_reason: 'Active financial fraud via UPI payment system.',
      technical_reason: 'UPI Collect request abuse combined with caller ID spoofing.',
      review_required: true, manual_review_reason: 'Active financial fraud — alert bank fraud team immediately',
      risk_breakdown: { credential_theft: 30, financial_loss: 95, identity_theft: 20, malware: 5, social_engineering: 90 },
    }),
  },
  {
    id: 'job-scam', title: 'Job Offer Scam', category: 'Employment Fraud', difficulty: 'beginner',
    description: 'Fake job offer requiring payment for "training" and "registration". Targets fresh graduates.',
    icon: '💼',
    result: makeResult({
      prediction: 'scam', confidence: 0.84, risk_level: 'high', scam_category: 'employment_fraud',
      summary: 'Fake job offer from impersonated company. Requires upfront payment for training materials and registration fees.',
      reasons: ['Unsolicited job offer with high salary', 'Requires payment for training', 'Company name similar to legitimate firm', 'No interview process'],
      suggested_action: 'warn', rule_score: 72, rule_label: 'HIGH_RISK', decision_score: 78, decision_level: 'suspicious',
      decision_reasoning: 'Upfront payment requirement is a strong fraud indicator.',
      entities: [
        { value: 'Amazon-India Careers', type: 'organization', confidence: 0.86, source: 'entity_extractor', risk: 'high', risk_reason: 'Impersonated Amazon recruitment' },
        { value: 'jobs@amazon-careers.co', type: 'email', confidence: 0.91, source: 'email_analysis', risk: 'high', risk_reason: 'Lookalike email domain' },
      ],
      entity_summary: { total_entities: 2, by_type: { organization: 1, email: 1 }, threat_indicators: ['Impersonated company', 'Fake email domain'] },
      entity_risk: { high: [
        { value: 'Amazon-India Careers', type: 'organization', confidence: 0.86, source: 'entity_extractor', risk: 'high', risk_reason: 'Impersonated company' },
        { value: 'jobs@amazon-careers.co', type: 'email', confidence: 0.91, source: 'email_analysis', risk: 'high', risk_reason: 'Fake email domain' },
      ], medium: [], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'message', source: 'email_analysis', description: 'Job offer from lookalike domain amazon-careers.co', severity: 'high', confidence: 0.91, weight: 8 },
        { id: 'ev2', type: 'behavioral', source: 'payment_request', description: 'Requires ₹2,500 for "training materials" before joining', severity: 'high', confidence: 0.88, weight: 8 },
        { id: 'ev3', type: 'behavioral', source: 'process_analysis', description: 'No interview process — direct job offer based on resume', severity: 'medium', confidence: 0.79, weight: 6 },
      ],
      conflicting_evidence: [],
      threats: ['Advance fee fraud', 'Identity document harvesting', 'Employment impersonation'],
      detected_indicators: ['Upfront payment requirement', 'Lookalike email domain', 'No interview process', 'Unsolicited high-salary offer'],
      recommended_actions: ['Block email domain', 'Warn job seekers', 'Report to cybercrime portal', 'Alert legitimate company'],
      recommended_priority: 'high', recommended_action: 'warn',
      assessment_score: 80, assessment_band: 'requires investigation', assessment_confidence: 'high',
      assessment_summary: 'Employment fraud targeting fresh graduates with fake job offers.',
      risk_breakdown: { credential_theft: 15, financial_loss: 75, identity_theft: 50, malware: 5, social_engineering: 85 },
    }),
  },
  {
    id: 'investment-scam', title: 'Investment Fraud Scheme', category: 'Investment Fraud', difficulty: 'advanced',
    description: 'Ponzi scheme disguised as cryptocurrency investment platform. Promises guaranteed 5% daily returns.',
    icon: '📈',
    result: makeResult({
      prediction: 'scam', confidence: 0.95, risk_level: 'critical', scam_category: 'investment_fraud',
      summary: 'Sophisticated Ponzi scheme operating as "crypto investment platform". Promises 5% daily returns with referral bonuses.',
      reasons: ['Guaranteed unrealistic returns (5% daily)', 'Referral bonus structure indicates pyramid scheme', 'No registered financial entity', 'Withdrawal blocked after initial deposits', 'Fake trading dashboard shows fabricated profits'],
      suggested_action: 'block', rule_score: 91, rule_label: 'CRITICAL_RISK', decision_score: 93, decision_level: 'critical',
      decision_reasoning: 'Classic Ponzi scheme indicators: guaranteed returns, referral pyramid, no real trading, blocked withdrawals.',
      entities: [
        { value: 'cryptoking-invest.com', type: 'domain', confidence: 0.97, source: 'url_parser', risk: 'high', risk_reason: 'Fraudulent investment platform' },
        { value: 'CryptoKing Investments', type: 'organization', confidence: 0.94, source: 'entity_extractor', risk: 'high', risk_reason: 'Unregistered investment entity' },
        { value: '45.67.89.12', type: 'ip', confidence: 0.89, source: 'dns_lookup', risk: 'high', risk_reason: 'Hosted in sanction-risk jurisdiction' },
      ],
      entity_summary: { total_entities: 3, by_type: { domain: 1, organization: 1, ip: 1 }, threat_indicators: ['Fraudulent platform', 'Unregistered entity', 'Sanction-risk hosting'] },
      entity_risk: { high: [
        { value: 'cryptoking-invest.com', type: 'domain', confidence: 0.97, source: 'url_parser', risk: 'high', risk_reason: 'Fraudulent platform' },
        { value: 'CryptoKing Investments', type: 'organization', confidence: 0.94, source: 'entity_extractor', risk: 'high', risk_reason: 'Unregistered entity' },
        { value: '45.67.89.12', type: 'ip', confidence: 0.89, source: 'dns_lookup', risk: 'high', risk_reason: 'Sanction-risk jurisdiction' },
      ], medium: [], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'financial', source: 'promise_analysis', description: 'Guarantees 5% daily returns — mathematically impossible for legitimate investment', severity: 'critical', confidence: 0.97, weight: 10 },
        { id: 'ev2', type: 'behavioral', source: 'referral_analysis', description: 'Multi-level referral bonus structure paying 10% commission on deposits', severity: 'high', confidence: 0.94, weight: 9 },
        { id: 'ev3', type: 'technical', source: 'registration_check', description: 'Not registered with SEBI or any financial regulator', severity: 'high', confidence: 0.96, weight: 9 },
        { id: 'ev4', type: 'behavioral', source: 'withdrawal_analysis', description: 'Multiple reports of withdrawal requests blocked after initial deposits', severity: 'critical', confidence: 0.93, weight: 9 },
      ],
      conflicting_evidence: [
        { id: 'cev1', type: 'technical', source: 'ssl_check', description: 'Website has valid SSL certificate', severity: 'low', confidence: 0.5, weight: 1 },
      ],
      threats: ['Ponzi scheme / pyramid scheme', 'Cryptocurrency investment fraud', 'Money laundering via crypto', 'Referral-based victim recruitment'],
      detected_indicators: ['Guaranteed unrealistic returns', 'Multi-level referral structure', 'Unregistered financial entity', 'Withdrawal blocked', 'Fabricated trading dashboard', 'Pressure to recruit others'],
      recommended_actions: ['Block website immediately', 'Report to SEBI', 'Report to cybercrime portal', 'Warn potential investors on social media', 'Add to investment fraud database', 'Trace cryptocurrency wallet addresses'],
      recommended_priority: 'urgent', recommended_action: 'block',
      assessment_score: 95, assessment_band: 'requires immediate action', assessment_confidence: 'high',
      assessment_summary: 'Confirmed Ponzi scheme operating as crypto investment platform.',
      business_reason: 'Large-scale investment fraud scheme targeting retail investors.',
      technical_reason: 'Platform hosted in sanction-risk jurisdiction. No real trading infrastructure.',
      review_required: true, manual_review_reason: 'Major investment fraud — escalate to financial crimes unit',
      risk_breakdown: { credential_theft: 10, financial_loss: 98, identity_theft: 30, malware: 15, social_engineering: 85 },
      connector_matches: [
        { connector_name: 'ThreatFox', source: 'abuse.ch', verdict: 'malicious', confidence: 0.93 },
        { connector_name: 'AlienVault OTX', source: 'otx.alienvault.com', verdict: 'malicious', confidence: 0.91 },
      ],
      knowledge_matches: [
        { pattern: 'Ponzi scheme — guaranteed returns', label: 'Crypto Ponzi v3', similarity: 0.96 },
        { pattern: 'Investment fraud — referral pyramid', label: 'MLM Fraud Pattern', similarity: 0.91 },
      ],
      threat_intel_fusion: { overall_verdict: 'malicious', overall_confidence: 0.94, overall_severity: 'critical', agreement_score: 0.92, source_count: 3 },
      investigation_report: { technique: 'Ponzi Scheme', ttps: ['T1548', 'T1190'], iocs: ['cryptoking-invest.com', '45.67.89.12'] },
    }),
  },
  {
    id: 'lottery-scam', title: 'Lottery Prize Scam', category: 'Prize Fraud', difficulty: 'beginner',
    description: 'Fake lottery winning notification. Victim asked to pay processing fee to claim non-existent prize.',
    icon: '🎰',
    result: makeResult({
      prediction: 'scam', confidence: 0.91, risk_level: 'high', scam_category: 'prize_fraud',
      summary: 'Fake lottery winning notification claiming the recipient won ₹25 lakh. Requires processing fee payment.',
      reasons: ['Unsolicited winning notification', 'Request for processing fee', 'No legitimate lottery entry found', 'Generic greeting without name'],
      suggested_action: 'warn', rule_score: 80, rule_label: 'HIGH_RISK', decision_score: 84, decision_level: 'suspicious',
      decision_reasoning: 'Classic advance fee fraud: prize notification followed by payment request.',
      entities: [
        { value: 'KBC Lucky Draw', type: 'organization', confidence: 0.88, source: 'entity_extractor', risk: 'high', risk_reason: 'Impersonated KBC lottery' },
        { value: 'claim@kbc-winner.co', type: 'email', confidence: 0.92, source: 'email_analysis', risk: 'high', risk_reason: 'Fraudulent claim email domain' },
      ],
      entity_summary: { total_entities: 2, by_type: { organization: 1, email: 1 }, threat_indicators: ['Impersonated KBC lottery', 'Fake claim email'] },
      entity_risk: { high: [
        { value: 'KBC Lucky Draw', type: 'organization', confidence: 0.88, source: 'entity_extractor', risk: 'high', risk_reason: 'Impersonated KBC lottery' },
        { value: 'claim@kbc-winner.co', type: 'email', confidence: 0.92, source: 'email_analysis', risk: 'high', risk_reason: 'Fake claim email' },
      ], medium: [], low: [] },
      supporting_evidence: [
        { id: 'ev1', type: 'message', source: 'sms_analysis', description: 'Generic "Congratulations! You won ₹25 lakh!" message', severity: 'high', confidence: 0.91, weight: 8 },
        { id: 'ev2', type: 'behavioral', source: 'payment_request', description: 'Requires ₹5,000 processing fee to release prize', severity: 'critical', confidence: 0.94, weight: 9 },
        { id: 'ev3', type: 'behavioral', source: 'verification', description: 'No record of user entering any lottery or contest', severity: 'high', confidence: 0.89, weight: 7 },
      ],
      conflicting_evidence: [],
      threats: ['Advance fee fraud', 'Prize scam', 'Impersonation of KBC / lottery brands'],
      detected_indicators: ['Unsolicited winning notification', 'Processing fee required', 'Generic greeting', 'Lookalike email domain', 'Impersonated brand'],
      recommended_actions: ['Block email domain', 'Warn recipient', 'Report to cybercrime portal', 'Add SMS filter rule'],
      recommended_priority: 'high', recommended_action: 'warn',
      assessment_score: 86, assessment_band: 'requires investigation', assessment_confidence: 'high',
      assessment_summary: 'Classic advance fee fraud disguised as lottery winning.',
      risk_breakdown: { credential_theft: 10, financial_loss: 80, identity_theft: 35, malware: 5, social_engineering: 85 },
    }),
  },
];
