limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;
limit_req_zone $binary_remote_addr zone=static:10m rate=100r/s;
limit_req_status 429;

include /etc/nginx/slots/*.conf;
include /etc/nginx/certs/*.conf;

upstream frontend {
    server frontend:80;
}

server {
    listen 80 default_server;
    server_name _;
    include /etc/nginx/routes.conf;
}
