__all__ = [
    "EVIDENCE_MAX_HIGH_ENTITIES", "EVIDENCE_MAX_MEDIUM_ENTITIES", "EVIDENCE_MAX_FINDINGS",
    "DECISION_MAX_WEIGHT", "DECISION_HIGH_BONUS_THRESHOLD", "DECISION_HIGH_BONUS2_THRESHOLD",
    "DECISION_HIGH_BONUS", "DECISION_CONFLICT_PENALTY",
    "ASSESSMENT_ML_WEIGHT", "ASSESSMENT_DECISION_WEIGHT", "ASSESSMENT_EVIDENCE_WEIGHT",
    "ASSESSMENT_INDICATOR_WEIGHT", "ASSESSMENT_ENTITY_WEIGHT", "ASSESSMENT_CONFLICT_PENALTY",
    "ASSESSMENT_MAX_SCORE", "ASSESSMENT_MAX_ML_POINTS", "ASSESSMENT_MAX_DECISION_POINTS",
    "ASSESSMENT_MAX_EVIDENCE_POINTS", "ASSESSMENT_MAX_INDICATOR_POINTS", "ASSESSMENT_MAX_ENTITY_POINTS",
    "ASSESSMENT_MAX_CONFLICT_PENALTY", "ASSESSMENT_EVIDENCE_HIGH_CAP", "ASSESSMENT_EVIDENCE_MED_CAP",
    "ASSESSMENT_EVIDENCE_HIGH_POINTS", "ASSESSMENT_EVIDENCE_MED_POINTS",
    "ASSESSMENT_MANUAL_REVIEW_CONFIDENCE_THRESHOLD",
    "CONFIDENCE_BREAKDOWN_ML_WEIGHT", "CONFIDENCE_BREAKDOWN_RULES_WEIGHT",
    "CONFIDENCE_BREAKDOWN_ENTITIES_WEIGHT", "CONFIDENCE_BREAKDOWN_EXPLANATION_WEIGHT",
    "HIGH_CONFIDENCE_THRESHOLD", "MEDIUM_CONFIDENCE_THRESHOLD", "LOW_CONFIDENCE_THRESHOLD",
]

EVIDENCE_MAX_HIGH_ENTITIES: int = 6
EVIDENCE_MAX_MEDIUM_ENTITIES: int = 6
EVIDENCE_MAX_FINDINGS: int = 12

DECISION_MAX_WEIGHT: int = 100
DECISION_HIGH_BONUS_THRESHOLD: int = 3
DECISION_HIGH_BONUS2_THRESHOLD: int = 5
DECISION_HIGH_BONUS: int = 5
DECISION_CONFLICT_PENALTY: int = 5

ASSESSMENT_ML_WEIGHT: float = 0.25
ASSESSMENT_DECISION_WEIGHT: float = 0.30
ASSESSMENT_EVIDENCE_WEIGHT: float = 0.20
ASSESSMENT_INDICATOR_WEIGHT: float = 0.10
ASSESSMENT_ENTITY_WEIGHT: float = 0.10
ASSESSMENT_CONFLICT_PENALTY: float = 0.05
ASSESSMENT_MAX_SCORE: int = 100
ASSESSMENT_MAX_ML_POINTS: int = 25
ASSESSMENT_MAX_DECISION_POINTS: int = 30
ASSESSMENT_MAX_EVIDENCE_POINTS: int = 20
ASSESSMENT_MAX_INDICATOR_POINTS: int = 10
ASSESSMENT_MAX_ENTITY_POINTS: int = 10
ASSESSMENT_MAX_CONFLICT_PENALTY: int = 3
ASSESSMENT_EVIDENCE_HIGH_CAP: int = 15
ASSESSMENT_EVIDENCE_MED_CAP: int = 6
ASSESSMENT_EVIDENCE_HIGH_POINTS: int = 5
ASSESSMENT_EVIDENCE_MED_POINTS: int = 2
ASSESSMENT_MANUAL_REVIEW_CONFIDENCE_THRESHOLD: float = 0.7

CONFIDENCE_BREAKDOWN_ML_WEIGHT: float = 0.25
CONFIDENCE_BREAKDOWN_RULES_WEIGHT: float = 0.30
CONFIDENCE_BREAKDOWN_ENTITIES_WEIGHT: float = 0.20
CONFIDENCE_BREAKDOWN_EXPLANATION_WEIGHT: float = 0.25

HIGH_CONFIDENCE_THRESHOLD: float = 0.8
MEDIUM_CONFIDENCE_THRESHOLD: float = 0.7
LOW_CONFIDENCE_THRESHOLD: float = 0.4
