__all__ = [
    "AUTH_ENABLED", "AUTH_JWT_SECRET", "AUTH_JWT_ALGORITHM",
    "AUTH_ACCESS_TOKEN_TTL", "AUTH_REFRESH_TOKEN_TTL",
    "ADMIN_API_KEY", "CLIENT_API_KEY",
    "JWT_CLOCK_SKEW_SECONDS", "TOKEN_BLACKLIST_CAPACITY",
    "REDIS_URL", "AUTH_RATE_LIMIT_MAX", "AUTH_RATE_LIMIT_WINDOW",
    "AUTH_ADMIN_RATE_LIMIT_MAX", "AUTH_ADMIN_RATE_LIMIT_WINDOW",
    "AUTH_SECRET_MIN_LENGTH", "AUTH_API_KEY_MIN_LENGTH",
    "REGISTER_ENABLED", "PASSWORD_MIN_LENGTH", "PASSWORD_MAX_LENGTH",
    "PASSWORD_REQUIRE_LETTER", "PASSWORD_REQUIRE_NUMBER",
    "LOCKOUT_THRESHOLD", "LOCKOUT_SECONDS",
]

AUTH_ENABLED: bool = False
AUTH_JWT_SECRET: str = ""
AUTH_JWT_ALGORITHM: str = "HS256"
AUTH_ACCESS_TOKEN_TTL: int = 3600
AUTH_REFRESH_TOKEN_TTL: int = 86400 * 30
ADMIN_API_KEY: str = ""
CLIENT_API_KEY: str = ""
JWT_CLOCK_SKEW_SECONDS: int = 30
TOKEN_BLACKLIST_CAPACITY: int = 100000
AUTH_SECRET_MIN_LENGTH: int = 32
AUTH_API_KEY_MIN_LENGTH: int = 16

REGISTER_ENABLED: bool = True
PASSWORD_MIN_LENGTH: int = 10
PASSWORD_MAX_LENGTH: int = 128
PASSWORD_REQUIRE_LETTER: bool = True
PASSWORD_REQUIRE_NUMBER: bool = True
LOCKOUT_THRESHOLD: int = 5
LOCKOUT_SECONDS: int = 300

REDIS_URL: str = ""
AUTH_RATE_LIMIT_MAX: int = 20
AUTH_RATE_LIMIT_WINDOW: int = 60
AUTH_ADMIN_RATE_LIMIT_MAX: int = 10
AUTH_ADMIN_RATE_LIMIT_WINDOW: int = 60
