__all__ = [
    "AUTH_ENABLED", "AUTH_JWT_SECRET", "AUTH_JWT_ALGORITHM",
    "AUTH_ACCESS_TOKEN_TTL", "AUTH_REFRESH_TOKEN_TTL",
    "ADMIN_API_KEY", "JWT_CLOCK_SKEW_SECONDS", "TOKEN_BLACKLIST_CAPACITY",
    "REDIS_URL", "AUTH_RATE_LIMIT_MAX", "AUTH_RATE_LIMIT_WINDOW",
    "AUTH_ADMIN_RATE_LIMIT_MAX", "AUTH_ADMIN_RATE_LIMIT_WINDOW",
]

AUTH_ENABLED: bool = False
AUTH_JWT_SECRET: str = ""
AUTH_JWT_ALGORITHM: str = "HS256"
AUTH_ACCESS_TOKEN_TTL: int = 3600
AUTH_REFRESH_TOKEN_TTL: int = 86400 * 30
ADMIN_API_KEY: str = ""
JWT_CLOCK_SKEW_SECONDS: int = 30
TOKEN_BLACKLIST_CAPACITY: int = 100000

REDIS_URL: str = ""
AUTH_RATE_LIMIT_MAX: int = 20
AUTH_RATE_LIMIT_WINDOW: int = 60
AUTH_ADMIN_RATE_LIMIT_MAX: int = 10
AUTH_ADMIN_RATE_LIMIT_WINDOW: int = 60
