__all__ = [
    "CONNECTOR_ENABLED", "CONNECTOR_TIMEOUT", "CONNECTOR_RETRY_COUNT", "CONNECTOR_PARALLELISM",
    "CONNECTOR_CACHE_TTL", "CONNECTOR_MAX_RESULTS",
    "SAFE_BROWSING_ENABLED", "SAFE_BROWSING_API_KEY", "SAFE_BROWSING_TIMEOUT",
    "SAFE_BROWSING_CACHE_TTL", "SAFE_BROWSING_MAX_BATCH",
    "FUSION_SOURCE_WEIGHTS", "FUSION_AGREEMENT_THRESHOLD", "FUSION_CONFLICT_THRESHOLD", "FUSION_MIN_SOURCES",
]

from typing import Dict

CONNECTOR_ENABLED: bool = True
CONNECTOR_TIMEOUT: int = 10
CONNECTOR_RETRY_COUNT: int = 1
CONNECTOR_PARALLELISM: int = 4
CONNECTOR_CACHE_TTL: int = 300
CONNECTOR_MAX_RESULTS: int = 10

SAFE_BROWSING_ENABLED: bool = True
SAFE_BROWSING_API_KEY: str = ""
SAFE_BROWSING_TIMEOUT: int = 15
SAFE_BROWSING_CACHE_TTL: int = 300
SAFE_BROWSING_MAX_BATCH: int = 500

FUSION_SOURCE_WEIGHTS: Dict[str, float] = {
    "google_safe_browsing": 0.90,
    "mock_threat": 0.80,
}
FUSION_AGREEMENT_THRESHOLD: float = 0.5
FUSION_CONFLICT_THRESHOLD: float = 0.3
FUSION_MIN_SOURCES: int = 1
