__all__ = [
    "INVESTIGATION_ENTITY_CONFIDENCE_BOOST", "INVESTIGATION_ENTITY_MAX_CONFIDENCE",
    "INVESTIGATION_CAMPAIGN_MIN_ARTEFACTS", "INVESTIGATION_CAMPAIGN_CONFIDENCE_THRESHOLD",
    "INVESTIGATION_SHARED_ENTITY_OVERLAP_RATIO", "INVESTIGATION_GRAPH_MAX_NODES",
    "INVESTIGATION_GRAPH_MAX_EDGES", "INVESTIGATION_TIMELINE_MAX_EVENTS",
    "INVESTIGATION_GLOBAL_RISK_PEAK_WEIGHT", "INVESTIGATION_GLOBAL_RISK_AVG_WEIGHT",
    "INVESTIGATION_CAMPAIGN_BOOST", "INVESTIGATION_MAX_ENTITIES_PER_TYPE",
    "INVESTIGATION_MAX_STRONGEST_EVIDENCE", "INVESTIGATION_MAX_WEAKEST_SIGNALS",
    "INVESTIGATION_MAX_OPEN_QUESTIONS",
]

INVESTIGATION_ENTITY_CONFIDENCE_BOOST: float = 0.10
INVESTIGATION_ENTITY_MAX_CONFIDENCE: float = 1.0
INVESTIGATION_CAMPAIGN_MIN_ARTEFACTS: int = 2
INVESTIGATION_CAMPAIGN_CONFIDENCE_THRESHOLD: float = 0.3
INVESTIGATION_SHARED_ENTITY_OVERLAP_RATIO: float = 0.3
INVESTIGATION_GRAPH_MAX_NODES: int = 30
INVESTIGATION_GRAPH_MAX_EDGES: int = 40
INVESTIGATION_TIMELINE_MAX_EVENTS: int = 50
INVESTIGATION_GLOBAL_RISK_PEAK_WEIGHT: float = 0.6
INVESTIGATION_GLOBAL_RISK_AVG_WEIGHT: float = 0.4
INVESTIGATION_CAMPAIGN_BOOST: float = 0.15
INVESTIGATION_MAX_ENTITIES_PER_TYPE: int = 5
INVESTIGATION_MAX_STRONGEST_EVIDENCE: int = 5
INVESTIGATION_MAX_WEAKEST_SIGNALS: int = 5
INVESTIGATION_MAX_OPEN_QUESTIONS: int = 5
