__all__ = [
    "KNOWLEDGE_LEVENSHTEIN_THRESHOLD", "KNOWLEDGE_MAX_MATCHES",
    "KNOWLEDGE_PREFIX_MIN_LENGTH", "KNOWLEDGE_SUFFIX_MIN_LENGTH",
    "KNOWLEDGE_HISTORICAL_MIN_SHARED", "KNOWLEDGE_ADVISORY_MIN_RELEVANCE",
]

KNOWLEDGE_LEVENSHTEIN_THRESHOLD: int = 3
KNOWLEDGE_MAX_MATCHES: int = 10
KNOWLEDGE_PREFIX_MIN_LENGTH: int = 4
KNOWLEDGE_SUFFIX_MIN_LENGTH: int = 4
KNOWLEDGE_HISTORICAL_MIN_SHARED: int = 1
KNOWLEDGE_ADVISORY_MIN_RELEVANCE: float = 0.3
