__all__ = [
    "REASONING_EVIDENCE_HIGH_THRESHOLD", "REASONING_EVIDENCE_MEDIUM_THRESHOLD",
    "REASONING_MAX_PRIMARY_EVIDENCE", "REASONING_MAX_SUPPORTING_EVIDENCE",
    "REASONING_MAX_WEAK_EVIDENCE", "REASONING_MAX_CONTRADICTORY_EVIDENCE",
    "REASONING_MAX_IGNORED_EVIDENCE", "REASONING_GRAPH_MAX_NODES", "REASONING_GRAPH_MAX_EDGES",
    "REASONING_FAMILY_INDICATOR_WEIGHT", "REASONING_FAMILY_CATEGORY_BOOST",
    "REASONING_UNKNOWN_CATEGORY_PENALTY",
]

REASONING_EVIDENCE_HIGH_THRESHOLD: float = 8.0
REASONING_EVIDENCE_MEDIUM_THRESHOLD: float = 4.0
REASONING_MAX_PRIMARY_EVIDENCE: int = 5
REASONING_MAX_SUPPORTING_EVIDENCE: int = 8
REASONING_MAX_WEAK_EVIDENCE: int = 5
REASONING_MAX_CONTRADICTORY_EVIDENCE: int = 5
REASONING_MAX_IGNORED_EVIDENCE: int = 5
REASONING_GRAPH_MAX_NODES: int = 20
REASONING_GRAPH_MAX_EDGES: int = 30
REASONING_FAMILY_INDICATOR_WEIGHT: float = 20.0
REASONING_FAMILY_CATEGORY_BOOST: float = 35.0
REASONING_UNKNOWN_CATEGORY_PENALTY: float = 0.5
