__all__ = [
    "REFINEMENT_ENABLED", "REFINEMENT_FP_IMPACT_PER_RULE", "REFINEMENT_FN_IMPACT_PER_RULE",
    "REFINEMENT_MAX_FP_TOTAL", "REFINEMENT_MAX_FN_TOTAL", "REFINEMENT_SCORE_OVERRIDE_THRESHOLD",
    "REFINEMENT_FLIP_THRESHOLD_SCORE", "REFINEMENT_FN_FLIP_THRESHOLD_SCORE",
    "REFINEMENT_FN_FLIP_ADJUSTMENT_MIN", "REFINEMENT_BOUNDARY_PROXIMITY",
    "REFINEMENT_CONFIDENCE_NEAR_THRESHOLD_LOW", "REFINEMENT_CONFIDENCE_NEAR_THRESHOLD_HIGH",
]

REFINEMENT_ENABLED: bool = True
REFINEMENT_FP_IMPACT_PER_RULE: float = 0.15
REFINEMENT_FN_IMPACT_PER_RULE: float = 0.15
REFINEMENT_MAX_FP_TOTAL: int = 30
REFINEMENT_MAX_FN_TOTAL: int = 30
REFINEMENT_SCORE_OVERRIDE_THRESHOLD: int = 15
REFINEMENT_FLIP_THRESHOLD_SCORE: int = 40
REFINEMENT_FN_FLIP_THRESHOLD_SCORE: int = 51
REFINEMENT_FN_FLIP_ADJUSTMENT_MIN: int = 20
REFINEMENT_BOUNDARY_PROXIMITY: int = 3
REFINEMENT_CONFIDENCE_NEAR_THRESHOLD_LOW: float = 0.45
REFINEMENT_CONFIDENCE_NEAR_THRESHOLD_HIGH: float = 0.55
