__all__ = [
    "REPORT_MAX_FINDINGS", "REPORT_MAX_HIGH_RISK_ENTITIES",
    "REPORT_ENTITIES_PER_TYPE", "REPORT_KEY_FINDINGS", "REPORT_TOP_RISKS",
]

REPORT_MAX_FINDINGS: int = 12
REPORT_MAX_HIGH_RISK_ENTITIES: int = 8
REPORT_ENTITIES_PER_TYPE: int = 5
REPORT_KEY_FINDINGS: int = 4
REPORT_TOP_RISKS: int = 3
