import type { ReportContent } from '@/features/report/types';

export function exportJSON(report: ReportContent): Blob {
  const json = JSON.stringify(report, null, 2);
  return new Blob([json], { type: 'application/json;charset=utf-8' });
}

export function exportMarkdown(report: ReportContent): string {
  const lines: string[] = [];

  lines.push(`# ${report.title}`);
  lines.push('');
  lines.push(`**Generated:** ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push(`**Template:** ${report.template}`);
  lines.push(`**Prediction:** ${report.metadata.prediction.toUpperCase()}`);
  lines.push(`**Confidence:** ${(report.metadata.confidence * 100).toFixed(1)}%`);
  lines.push(`**Risk Level:** ${report.metadata.riskLevel}`);
  lines.push(`**Scam Category:** ${report.metadata.scamCategory}`);
  lines.push('');

  for (const section of report.sections) {
    lines.push(`## ${section.title}`);
    lines.push('');
    for (const line of section.content) {
      lines.push(line);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Report generated by Wary Investigation System*`);
  return lines.join('\n');
}

export function exportText(report: ReportContent): string {
  const lines: string[] = [];
  const sep = '='.repeat(60);

  lines.push(sep);
  lines.push(`  ${report.title}`);
  lines.push(sep);
  lines.push(`  Generated: ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push(`  Template: ${report.template}`);
  lines.push(`  Prediction: ${report.metadata.prediction.toUpperCase()}`);
  lines.push(`  Confidence: ${(report.metadata.confidence * 100).toFixed(1)}%`);
  lines.push(`  Risk Level: ${report.metadata.riskLevel}`);
  lines.push(`  Scam Category: ${report.metadata.scamCategory}`);
  lines.push('');

  for (const section of report.sections) {
    lines.push(section.title.toUpperCase());
    lines.push('-'.repeat(section.title.length));
    lines.push('');
    for (const line of section.content) {
      lines.push(`  ${line}`);
    }
    lines.push('');
  }

  lines.push(sep);
  lines.push('  Report generated by Wary Investigation System');
  lines.push(sep);
  return lines.join('\n');
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}

export function shareReport(report: ReportContent): void {
  if (navigator.share) {
    navigator.share({
      title: report.title,
      text: exportText(report).slice(0, 2000),
    }).catch(() => {});
  } else {
    copyToClipboard(exportText(report));
  }
}

export function printReport(report: ReportContent, renderContent: () => string): void {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head><title>${report.title}</title>`);
  win.document.write('<style>body{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.6;color:#1a1a2e;}');
  win.document.write('h1{font-size:24px;border-bottom:2px solid #059669;padding-bottom:8px;}');
  win.document.write('h2{font-size:18px;color:#059669;margin-top:32px;}');
  win.document.write('.meta{background:#f4f4f5;padding:16px;border-radius:8px;font-size:14px;}');
  win.document.write('.section{white-space:pre-wrap;font-size:14px;}');
  win.document.write('@media print{body{margin:20px;}.no-print{display:none;}}');
  win.document.write('</style></head><body>');
  win.document.write(`<h1>${report.title}</h1>`);
  win.document.write('<div class="meta">');
  win.document.write(`<p><strong>Generated:</strong> ${new Date(report.generatedAt).toLocaleString()}</p>`);
  win.document.write(`<p><strong>Prediction:</strong> ${report.metadata.prediction.toUpperCase()} | <strong>Confidence:</strong> ${(report.metadata.confidence * 100).toFixed(1)}% | <strong>Risk:</strong> ${report.metadata.riskLevel}</p>`);
  win.document.write(`<p><strong>Scam Category:</strong> ${report.metadata.scamCategory}</p>`);
  win.document.write('</div>');
  win.document.write('<div class="section">');
  win.document.write(renderContent().replace(/\n/g, '<br>'));
  win.document.write('</div>');
  win.document.write('<p class="no-print" style="margin-top:40px;text-align:center;color:#999;">Generated by Wary</p>');
  win.document.write('</body></html>');
  win.document.close();
  win.focus();
}
